#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts Example (service)
# ==============================================================================
# shellcheck disable=SC1091
#source /usr/lib/hassio-addons/base.sh

echo ""
echo "MySensors Gateway++"
MYSGW_TYPE=$(hass.jq "${CONFIG_PATH}" ".type")
MYSGW_TRN=$(hass.jq "${CONFIG_PATH}" ".transport")
MQTT_SERVER=$(hass.jq "${CONFIG_PATH}" ".mqtt_server")
MQTT_CLIENTID=$(hass.jq "${CONFIG_PATH}" ".mqtt_clientid")
MQTT_TOPIC_IN=$(hass.jq "${CONFIG_PATH}" ".mqtt_topicin")
MQTT_TOPIC_OUT=$(hass.jq "${CONFIG_PATH}" ".mqtt_topicout")

MQTT_OPTS="--spi-spidev-device=/dev/spidev0.0 --my-transport=$MYSGW_TRN --my-gateway=$MYSGW_TYPE --my-mqtt-client-id=$MQTT_CLIENTID --my-controller-ip-address=$MQTT_SERVER --my-mqtt-publish-topic-prefix=$MQTT_TOPIC_OUT --my-mqtt-subscribe-topic-prefix=$MQTT_TOPIC_IN"

echo ""
hass.log.info " Configuration:"
hass.log.info "   MYSGW_TYPE = '${MYSGW_TYPE}'"
hass.log.info "   MYSGW_TRN = '${MYSGW_TRN}'"
hass.log.info "   MQTT_SERVER = '${MQTT_SERVER}'"
hass.log.info "   MQTT_CLIENTID = '${MQTT_CLIENTID}'"
hass.log.info "   MQTT_TOPIC_IN = '${MQTT_TOPIC_IN}'"
hass.log.info "   MQTT_TOPIC_OUT = '${MQTT_TOPIC_OUT}'"
echo ""
hass.log.info "   MQTT_OPTS = '${MQTT_OPTS}'"

hass.log.info 'Test hass.log.info'
hass.log.debug 'Test hass.log.debug'
hass.log.warning 'Test hass.log.warning'

echo "[Info] Change dir to '${APPDIR}'"
cd $APPDIR
echo "[Info] Make"
./configure $MQTT_OPTS
echo "[Info] Make"
make 
# echo "[Info] Make install"
# make install
# echo "[Info] Gateway Help"
# exec ./bin/mysgw --help
echo "[Info] Run Gateway"
#exec ./bin/mysgw -c /config/mysensors/mysensors.conf
exec ./bin/mysgw
echo "[Info] Finished run Gateway"