#!/usr/bin/with-contenv bash
# ==============================================================================
# Starts Example (service)
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

echo ""
echo "MySensors Gateway++"
MYSGW_TYPE=$(hass.jq "${CONFIG_PATH}" ".type")
MYSGW_TRN=$(hass.jq "${CONFIG_PATH}" ".transport")
MQTT_SERVER=$(hass.jq "${CONFIG_PATH}" ".mqtt_server")
MQTT_CLIENTID=$(hass.jq "${CONFIG_PATH}" ".mqtt_clientid")
MQTT_TOPIC_IN=$(hass.jq "${CONFIG_PATH}" ".mqtt_topicin")
MQTT_TOPIC_OUT=$(hass.jq "${CONFIG_PATH}" ".mqtt_topicout")

MQTT_OPTS="--spi-spidev-device=/dev/spidev0.0 --my-transport=$MYSGW_TRN --my-gateway=$MYSGW_TYPE --my-mqtt-client-id=$MQTT_CLIENTID --my-controller-ip-address=$MQTT_SERVER --my-mqtt-publish-topic-prefix=$MQTT_TOPIC_OUT --my-mqtt-subscribe-topic-prefix=$MQTT_TOPIC_IN"

echo ""
echo "[Info] Configuration:"
echo "[Info]   MYSGW_TYPE = '${MYSGW_TYPE}'"
echo "[Info]   MYSGW_TRN = '${MYSGW_TRN}'"
echo "[Info]   MQTT_SERVER = '${MQTT_SERVER}'"
echo "[Info]   MQTT_CLIENTID = '${MQTT_CLIENTID}'"
echo "[Info]   MQTT_TOPIC_IN = '${MQTT_TOPIC_IN}'"
echo "[Info]   MQTT_TOPIC_OUT = '${MQTT_TOPIC_OUT}'"
echo ""
echo "[Info]   MQTT_OPTS = '${MQTT_OPTS}'"

echo "[Info] Change dir to '${APPDIR}'"
cd $APPDIR
echo "[Info] Make"
./configure $MQTT_OPTS
echo "[Info] Make"
sudo make && make install
echo "[Info] Run Gateway"
# sudo ./bin/mysgw 
EXEC ./bin/mysgw